// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function getDatabaseUrl(): string {
  const url = process.env["DATABASE_URL"];
  if (url) return url;
  const user = process.env["POSTGRES_DB_USER"];
  const password = process.env["POSTGRES_DB_PASSWORD"];
  const dbName = process.env["POSTGRES_DB_NAME"];
  const port = process.env["POSTGRES_PORT"] ?? "5432";
  const host = process.env["POSTGRES_HOST"] ?? "localhost";
  if (user && password && dbName) {
    return `postgresql://${encodeURIComponent(user)}:${encodeURIComponent(password)}@${host}:${port}/${encodeURIComponent(dbName)}`;
  }
  throw new Error(
    "Set DATABASE_URL or POSTGRES_DB_USER, POSTGRES_DB_PASSWORD, POSTGRES_DB_NAME (and optionally POSTGRES_PORT, POSTGRES_HOST)",
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: getDatabaseUrl(),
  },
});
